name: Manter Servidor Ativo

on:
  schedule:
    - cron: "*/9 * * * *"

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer requisição para a API
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://gamo-api.onrender.com/api/consoles"
          method: "GET"
