name: Manter Servidor Ativo

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Manter servidor ativo
        run: |
          echo "🔔 Enviando ping para manter servidor ativo..."

          # Simplesmente tenta fazer a requisição, ignora erros
          curl -s --max-time 120 "https://gamo-api.onrender.com/api/consoles" || true

          echo "📞 Requisição enviada - servidor deve permanecer ativo"
          echo "✅ Workflow concluído com sucesso"
